#!/bin/bash
# Step 1 function
step_1() {
    wget https://raw.githubusercontent.com/sheid1309/DevOps-Scripts/master/docker.sh
    chmod u+x docker.sh
    . docker.sh
    rm -rf docker.sh
    . install.sh
}

# Step 2 function
step_2(){
    export ENV=http
    docker-compose up -d --build
    . install.sh
}

# Step 3 function
step_3(){
    docker rm -f certbot
    docker run -it --name certbot \
    -v certbot-etc:/etc/letsencrypt \
    -v certbot-var:/var/lib/letsencrypt \
    -v web-root:/home/plybi \
    certbot/certbot \
    certonly --webroot --webroot-path=/home/plybi --agree-tos --no-eff-email -d plybi.com -d www.plybi.com
    . install.sh
}

# Step 4 function
step_4(){
    docker cp nginx/my-default-https.conf nginx:/etc/nginx/conf.d/default.conf
    docker-compose restart
    . install.sh
}

# Step 5 function
step_5(){
    export ENV=https
    docker-compose down
    docker-compose up -d --build
    . install.sh
}